# Generated by Django 5.2.4 on 2025-08-02 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('final_title', models.CharField(blank=True, max_length=255)),
                ('is_final_approved', models.BooleanField(default=False)),
                ('editor_status', models.CharField(choices=[('pending', 'بإنتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20)),
                ('thumbnail_status', models.CharField(choices=[('pending', 'بإنتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'بإنتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20)),
                ('youtuber_status', models.CharField(choices=[('pending', 'بإنتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20)),
                ('uploading_status', models.CharField(choices=[('pending', 'بإنتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
