# Generated by Django 5.2.4 on 2025-08-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'فيديو', 'verbose_name_plural': 'الفيديوهات'},
        ),
        migrations.AlterField(
            model_name='video',
            name='editor_status',
            field=models.CharField(choices=[('pending', 'بانتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20, verbose_name='حالة المنتج'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/', verbose_name='ملف الفيديو'),
        ),
        migrations.AlterField(
            model_name='video',
            name='final_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان النهائي'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_final_approved',
            field=models.BooleanField(default=False, verbose_name='تمت الموافقة النهائية'),
        ),
        migrations.AlterField(
            model_name='video',
            name='review_status',
            field=models.CharField(choices=[('pending', 'بانتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20, verbose_name='حالة المراجع'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_status',
            field=models.CharField(choices=[('pending', 'بانتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20, verbose_name='حالة المصمم'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='اليوتيوبر'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploading_status',
            field=models.CharField(choices=[('pending', 'بانتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20, verbose_name='حالة الرفع'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtuber_status',
            field=models.CharField(choices=[('pending', 'بانتظار البدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم الانتهاء')], default='pending', max_length=20, verbose_name='حالة اليوتيوبر'),
        ),
    ]
