# Generated by Django 5.2.4 on 2025-08-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnail', '0001_initial'),
        ('videos', '0002_alter_video_options_alter_video_editor_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'verbose_name': 'ثمنيل', 'verbose_name_plural': 'الثمنيلات'},
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='designer',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مصمم الثمنيل'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(upload_to='thumbnails/', verbose_name='الصورة المصغرة'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='notes_from_reviewer',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المراجع'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='الفيديو المرتبط'),
        ),
    ]
