# Generated by Django 5.2.4 on 2025-08-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'إعداد الموقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/logo/', verbose_name='شعار الموقع'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(max_length=100, verbose_name='اسم الموقع'),
        ),
    ]
