# Generated by Django 5.2.4 on 2025-08-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
        ('videos', '0002_alter_video_options_alter_video_editor_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editedvideo',
            options={'verbose_name': 'فيديو منتج', 'verbose_name_plural': 'الفيديوهات المنتجة'},
        ),
        migrations.AlterField(
            model_name='editedvideo',
            name='editor',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'editor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='editedvideo',
            name='file',
            field=models.FileField(upload_to='edited_videos/', verbose_name='الفيديو بعد المونتاج'),
        ),
        migrations.AlterField(
            model_name='editedvideo',
            name='notes_from_reviewer',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المراجع'),
        ),
        migrations.AlterField(
            model_name='editedvideo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='editedvideo',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='الفيديو الأصلي'),
        ),
    ]
