# Generated by Django 5.2.4 on 2025-08-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0001_initial'),
        ('videos', '0002_alter_video_options_alter_video_editor_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadstatus',
            options={'verbose_name': 'حالة الرفع', 'verbose_name_plural': 'حالات الرفع'},
        ),
        migrations.AlterField(
            model_name='uploadstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'لم يبدأ'), ('uploading', 'جاري الرفع'), ('uploaded', 'تم الرفع')], default='not_started', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='uploadstatus',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='uploadstatus',
            name='uploader',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'uploader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسؤول الرفع'),
        ),
        migrations.AlterField(
            model_name='uploadstatus',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='الفيديو'),
        ),
    ]
