# Generated by Django 5.2.4 on 2025-08-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
        ('videos', '0002_alter_video_options_alter_video_editor_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalapproval',
            options={'verbose_name': 'موافقة نهائية', 'verbose_name_plural': 'الموافقات النهائية'},
        ),
        migrations.AlterField(
            model_name='finalapproval',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='تمت الموافقة النهائية'),
        ),
        migrations.AlterField(
            model_name='finalapproval',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AlterField(
            model_name='finalapproval',
            name='final_title',
            field=models.CharField(max_length=255, verbose_name='اسم الفيديو النهائي'),
        ),
        migrations.AlterField(
            model_name='finalapproval',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات اليوتيوبر'),
        ),
        migrations.AlterField(
            model_name='finalapproval',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='الفيديو'),
        ),
        migrations.AlterField(
            model_name='finalapproval',
            name='youtuber',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'youtuber'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اليوتيوبر'),
        ),
    ]
