# Generated by Django 5.2.4 on 2025-08-02 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('editor_approved', models.BooleanField(default=False)),
                ('editor_notes', models.TextField(blank=True)),
                ('thumbnail_approved', models.BooleanField(default=False)),
                ('thumbnail_notes', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(limit_choices_to={'profile__role': 'reviewer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]
