# Generated by Django 5.2.4 on 2025-08-02 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('videos', '0002_alter_video_options_alter_video_editor_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'مراجعة', 'verbose_name_plural': 'المراجعات'},
        ),
        migrations.AlterField(
            model_name='review',
            name='editor_approved',
            field=models.BooleanField(default=False, verbose_name='تمت الموافقة على الفيديو'),
        ),
        migrations.AlterField(
            model_name='review',
            name='editor_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات على الفيديو'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'reviewer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المراجع'),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbnail_approved',
            field=models.BooleanField(default=False, verbose_name='تمت الموافقة على الثمنيل'),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbnail_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات على الثمنيل'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='الفيديو'),
        ),
    ]
