"""
Django settings for abo_5lod project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
import environ
import dj_database_url

# بيئة المشروع
env = environ.Env()
environ.Env.read_env()

# المسار الأساسي داخل المشروع
BASE_DIR = Path(__file__).resolve().parent.parent

# مفتاح الأمان
SECRET_KEY = env("SECRET_KEY", default='django-insecure-nzgh&(a8drruvx00z6k4(oevn0uw7svdx2rvmf0v1vv%m!-k75')

# وضع التطوير
DEBUG = env.bool("DEBUG", default=True)

# النطاقات المسموح بها
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# التطبيقات المثبتة
INSTALLED_APPS = [
    # Django الأساسي
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # إضافات خارجية مثبتة
    'cloudinary',
    'cloudinary_storage',
    'crispy_forms',
    'django_extensions',
    'rest_framework',
    'channels',

    # تطبيقات المشروع مع AppConfig لعرض الأسماء بالعربية في لوحة التحكم
    'core.apps.CoreConfig',
    'account.apps.AccountConfig',
    'videos.apps.VideosConfig',
    'editor.apps.EditorConfig',
    'thumbnail.apps.ThumbnailConfig',
    'review.apps.ReviewConfig',
    'approval.apps.ApprovalConfig',
    'uploading.apps.UploadingConfig',
    'chat.apps.ChatConfig',
    'notifications.apps.NotificationsConfig',
]

# وسطاء المعالجة
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ملف URL الرئيسي
ROOT_URLCONF = 'abo_5lod.urls'

# إعدادات القوالب
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# إعداد WSGI
WSGI_APPLICATION = 'abo_5lod.wsgi.application'

# إعداد ASGI لـ WebSocket (قنوات المحادثة)
ASGI_APPLICATION = 'abo_5lod.asgi.application'

# قاعدة البيانات
DATABASES = {
    'default': dj_database_url.config(default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}

# التحقق من كلمات المرور
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# اللغة والمنطقة الزمنية
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_TZ = True

# إعداد static والوسائط
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# إعداد Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default='your_cloud_name'),
    'API_KEY': env('CLOUDINARY_API_KEY', default='your_api_key'),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default='your_api_secret'),
}

# إعداد البريد الإلكتروني
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env("EMAIL_HOST", default='smtp.gmail.com')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default='example@gmail.com')
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default='your_password')

# الحقل الافتراضي للموديلات
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
